#!/bin/sh
ssh ubuntu@54.224.180.35 <<EOF
 ssh ubuntu@18.212.175.239 "echo export ROLEID=$(docker exec -it f19 vault read -format=json auth/approle/role/weatherrole/role-id | jq -r .data.role_id) > .bash_profile; echo export WST=$(docker exec -it f19 vault write -format=json -wrap-ttl=2m -f auth/approle/role/weatherrole/secret-id | jq -r .wrap_info.token) >> .bash_profile; source .bash_profile"
EOF
